language: python

python:
  - "3.8"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest

script:
  - pytest filtercascade/test.py

matrix:
  fast_finish: true

  include:
  - name: 'Black: format check'
    install:
    - pip install black
    script:
    - black --diff .

# Only initiate build on mainline branches
branches:
  only: master

# Suppress at least some emails
notifications:
  email:
    on_success: never
