version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  python-build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pip install --editable .
      - run: pip install black
      - run:
         name: Check format with Black
         command: black --check .
      - run:
          name: run tests
          command: |
            pip install pytest
            mkdir test-results
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  main:
    jobs:
      - python-build-and-test
